#84 JavaScript conversion changes
OptimistikSAS/svgedit pull request #85
Opened 2021-03-17 14:04 UTC by AgriyaDev5

## PR description

JavaScript conversion changes

2021-03-17 20:23 UTC, jfhenon requested changes

2021-03-17 20:23 UTC, jfhenon commented on src/editor/Editor.js
> +    var elements = document.getElementsByClassName("attr_changer");
should use const or let

2021-03-18 05:22 UTC, AgriyaDev5 commented on src/editor/Editor.js
> +    var elements = document.getElementsByClassName("attr_changer");
changes done

2021-03-18 05:54 UTC, jfhenon approved these changes

2021-03-18 05:54 UTC, merged